{{- if .Values.guacamole.configurationFiles }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "guacamole.fullname" . }}-configuration
data:
{{- range $key, $val := .Values.guacamole.configurationFiles }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}
{{- end -}}