apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "guacamole.fullname" . }}-guacd
  labels:
    {{- include "guacamole.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "guacamole.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "guacamole.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}-guacd
          image: "{{ .Values.guacd.repo }}:{{ .Values.guacd.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: guacd
              containerPort: 4822
              protocol: TCP
