apiVersion: v1
kind: Service
metadata:
  name: {{ include "guacamole.fullname" . }}-guacamole
  labels:
    {{- include "guacamole.labels" . | nindent 4 }}
spec:
  type: {{ .Values.guacamole.service.type }}
  ports:
    - port: {{ .Values.guacamole.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
