apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "guacamole.fullname" . }}-guacamole
  labels:
    {{- include "guacamole.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "guacamole.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "guacamole.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}-guacamole
          image: "{{ .Values.guacamole.repo }}:{{ .Values.guacamole.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: GUACD_HOSTNAME
              value: "{{ .Chart.Name }}-guacd"
            - name: GUACD_PORT
              value: "{{ .Values.guacd.service.port }}"
            - name: GUACAMOLE_HOME
              value: "/etc/guacamole"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
