{{- $fullName := include "guacamole.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "guacamole.name" . }}
    helm.sh/chart: {{ include "guacamole.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.guacamole.service.type }}
  ports:
    - port: {{ .Values.guacamole.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "guacamole.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
