# guacamole guacamole

guacd:
  repo: r1cebank/guacd
  tag: 1.1.0
  pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 4822

guacamole:
  repo: r1cebank/guacamole
  tag: 1.1.0
  pullPolicy: IfNotPresent
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 500Mi
    storageClass: nfs-client
  service:
    type: ClusterIP
    port: 80


postgres:
  repo: postgres
  tag: latest
  pullPolicy: IfNotPresent
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 8Gi
    storageClass: nfs-client
  service:
    type: ClusterIP
    port: 5432

imagePullSecrets: []
