apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "yopass.fullname" . }}
  labels:
    app: {{ template "yopass.name" . }}
    chart: {{ template "yopass.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "yopass.name" . }}
      release: {{ .Release.Name }}
  strategy:
    type: {{ .Values.deploymentStrategy }}
  {{- if ne .Values.deploymentStrategy "RollingUpdate" }}
    rollingUpdate: null
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ template "yopass.name" . }}
        release: {{ .Release.Name }}
{{- with .Values.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repo }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - "--memcached=localhost:11211"
      - name: {{ template "yopass.name" . }}-sc-memcached
        image: "{{ .Values.image.memcached.repo }}:{{ .Values.image.memcached.tag }}"
        args:
          - "-m 64"
